version: "3.9"

services:

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bomberfrog
      MYSQL_USER: bomberfrog
      MYSQL_PASSWORD: bomberfrog

  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql: {}